name: Test DevOps App

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose up --build -d

      - name: Wait for services
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8000/health | grep -q "OK"; then
              echo "Service is healthy"
              exit 0
            fi
            echo "Waiting for health check..."
            sleep 5
          done
          echo "Health check failed"
          docker-compose logs
          exit 1

      - name: Tear down
        run: docker compose down
